<?php
/**
 * LauncherGen - Windows Application Launcher Batch File Generator
 * Copyright (C) 2015-2016 Andrés Cordero
 * Web: https://github.com/Andrew67/launchergen
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
// Warning: This file will produce bad batch files unless line ending is set to CRLF
// .gitattributes will enforce this on checkout
// Seemingly unnecessary line-endings are needed when last line element is a PHP short echo

// Error method
function throw_error($reason) {
    header('HTTP/1.1 400 Bad Request');
    die('Unable to process request: ' . $reason);
}

// Windows dirname
// Extracts executable directory using Windows directory separator
function win_dirname($path) {
    $last_slash_pos = strrpos($path, '\\');
    if ($last_slash_pos === false)
        return "";
    else
        return substr($path, 0, $last_slash_pos);
}

// User selection to Windows code page mappings
$codepages = array(
    'us-ascii' => 437,
    'shift_jis' => 932,
    'iso-8859-1' => 1252,
    'utf-8' => 65001,
);

// Sanity check: encoding
if (empty($_POST['charset']) || !array_key_exists($_POST['charset'], $codepages)) {
    throw_error('Invalid charset specified. Allowable values: ' . join(', ', array_keys($codepages)));
}

// Sanity check: form arrays set
if (empty($_POST['name']) || empty($_POST['path']) || empty($_POST['flag'])) {
    throw_error('Missing application data.');
}
// Sanity check: no more than 20 applications
if (count($_POST['path']) > 20) {
    throw_error('Exceeded allowable number of applications (20).');
}

// Import values into namespace / set defaults
$names = $_POST['name'];
$paths = $_POST['path'];
$flags = $_POST['flag'];
$header = !empty($_POST['header']) ? $_POST['header'] : 'Application Launcher';
$list_header = !empty($_POST['list_header']) ? $_POST['list_header'] : 'Available applications:';
$prompt = !empty($_POST['prompt']) ? $_POST['prompt'] : 'Select an application by typing the number and pressing "Enter" (default=1):';
$bgcolor = !empty($_POST['bgcolor']) ? $_POST['bgcolor'] : '0'; // black
$fgcolor = !empty($_POST['fgcolor']) ? $_POST['fgcolor'] : '7'; // white
$active_codepage = $codepages[$_POST['charset']];

// Set batch file type and force download
header('Content-Disposition: attachment; filename="launcher.bat"');
header('Content-Type: application/bat');
?>
@echo off
rem Generated by LauncherGen
rem Web: http://launchergen.andrew67.com/
chcp <?=$active_codepage?> > nul
color <?=$bgcolor.$fgcolor?>


echo <?=$header?>

echo.
echo <?=$list_header?>

<?php foreach ($names as $n => $name): ?>
echo   [<?=$n+1?>] <?=$name?>

<?php endforeach; ?>
echo.
set /p selection="<?=$prompt?> "

<?php for ($i=1; $i<=count($names); ++$i): ?>
if "%selection%" == "<?=$i?>" goto :block<?=$i?>

<?php endfor; ?>
goto :block1

<?php foreach ($paths as $n => $path): ?>
:block<?=$n+1?>

cd "<?=win_dirname($path)?>"
start "<?=$names[$n]?>" "<?=$path?>" <?=$flags[$n]?>

exit

<?php endforeach; ?>